<Bar_de_recherche>:

    MDBoxLayout:
        size_hint: .95, None
        height: "50dp"
        pos_hint: {"center_x": .5, "center_y": .68}
        padding: 5
        spacing: 5

        canvas.before:
            Color:
                rgba: 1, 1, 1, 1
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [25]

        #Recherche
        MDIconButton:
            icon: "magnify"
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 0.3
        
        TextInput:
            id: search_input
            multiline: False
            hint_text: "Rechercher un lieu"
            on_text_validate: root.rechercher()
            background_color: 1,1,1,1
            foreground_color: 0, 0, 0, 1
            cursor_color: 0, 0, 0, 1
            size_hint_x: 1
            height: "40dp"
            padding: [10, 10]
            background_normal: ""
            background_active: ""

        #Profile
        MDIconButton:
            icon: "account-circle"
            theme_text_color: "Custom"
            text_color: 0, 0, 0, 0.8

      