
<Bar_de_recherche>:
    MDBoxLayout:
        size_hint: .95, None
        height: "50dp"
        width : "330dp"
        pos_hint: {"center_x": .5, "center_y": .95}

        canvas.after:
            Color:
                rgba: 1, 1, 1, 0.65
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [25]

        TextInput:
            background_color: 0, 0, 0, 0      # fond transparent
            foreground_color: 0, 0, 0, 1   
            cursor_color: 0,0,0,1
            hint_text: "rechercher un lieu"
            hint_text_color: 0.5, 0.5, 0.5, 1
            padding: [70, 20, 0, 0]
            pos_hint: {"center_x": .5 ,"center_y":.5}
            size_hint: .4, None
            width: "200dp"
            height: "50dp"
        

            