<Bar_de_recherche>:
   
    
    MDBoxLayout:
        size_hint: .95, None
        height: "50dp"
        width: "400dp"
        pos_hint: {"center_x": .5, "center_y": .5}

        canvas.after:
            Color:
                rgba: 1, 1, 1, 0.65
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [25]

        TextInput:
            id: search_input
            multiline: False
            on_text_validate: root.rechercher()
            background_color: 0,0,0,0
            foreground_color: 0,0,0,1
            cursor_color: 0,0,0,1
            hint_text: "rechercher un lieu"
            padding: [70,20,0,0]
            size_hint: .4, None
            width: "200dp"
            height: "50dp"