<BarreRetour>:
    size_hint_y: None
    height: dp(56)
    orientation: "horizontal"

    canvas.before:
        Color:
            rgba: 1, 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        text: root.titre
        font_size: dp(20)
        bold: True
        color: 0, 0, 0, 1
        halign: "center"
        valign: "center"
        text_size: self.size
        padding: [0, dp(10), 0, 0]    # ← pousse le texte vers le bas