
<DetailTaximoto>:
    BoxLayout: 
        id:detail_widget
        orientation: "vertical"
        size_hint_y: None
        height: dp(320)              
        pos_hint: {"top": .9}         
        padding: dp(15)
        spacing: dp(10)

        canvas.before:
            Color:
                rgba: 0.96, 0.96, 0.96, 1
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [dp(15)]

        BoxLayout:
            size_hint_y: None
            height: dp(80)
            spacing: dp(10)
    
            AsyncImage:
                source: "image/utilisateur-50.png"
                size_hint: None, None
                size: dp(55), dp(55)
                pos_hint: {"center_y": 0.5}
                radius : [dp(10)]

            BoxLayout:
                orientation: "vertical"
                spacing: dp(4)

                Label:
                    text: root.nom
                    font_size: dp(18)
                    bold: True
                    color: 0, 0, 0, 1
                    halign: "left"
                    text_size: self.size
                    valign: "center"

                BoxLayout:
                    orientation: "horizontal"
                    size_hint_y: None
                    height: dp(28)
                    spacing: dp(6)

                    Label:
                        text: "Dispo" if root.disponibile else "Indisponible"
                        font_size: dp(14)
                        color: (0, 0.6, 0, 1) if root.disponibile else (0.8, 0, 0, 1)
                        halign: "left"
                        text_size: self.size
                        valign: "center"
                        
                    Label:
                        text: root.lieu
                        font_size: dp(14)
                        color: 0.5, 0.5, 0.5, 1
                        halign: "left"
                        text_size: self.size
                        valign: "center"

                    
            
            AsyncImage:
                source: "image/images.png"
                size_hint: None, None
                size: dp(90), dp(70)
                pos_hint: {"center_y": 0.5}

        BoxLayout:
            size_hint_y: None
            height: dp(1)
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

        BoxLayout:
            orientation: "vertical"
            size_hint_y: None
            height: dp(120)
            spacing: dp(6)
            padding: [0, dp(5), 0, 0]

            Label:
                text: "Description"
                font_size: dp(17)
                bold: True
                color: 0, 0, 0, 1
                halign: "left"
                text_size: self.size
                size_hint_y: None
                height: dp(25)

            Label:
                text: root.description
                font_size: dp(13)
                bold: True
                color: 0.2, 0.2, 0.2, 1
                halign: "center"
                valign: "top"
                text_size: self.size

        BoxLayout:
            size_hint_y: None
            height: dp(1)
            canvas.before:
                Color:
                    rgba: 0.85, 0.85, 0.85, 1
                Rectangle:
                    pos: self.pos
                    size: self.size

        BoxLayout:
            size_hint_y: None
            height: dp(60)
            spacing: dp(30)
            padding: [dp(20), dp(5), dp(20), dp(5)]

            # Facebook
            Button:
                size_hint: None, None
                size: dp(40), dp(40)
                pos_hint: {"center_y": 0.5}
                background_color: 0, 0, 0, 0
                on_press: print("Facebook")

                Image:
                    source: "image/facebook-24.png"
                    size: dp(32), dp(32)
                    size_hint: None, None
                    center: self.parent.center
            Button:
                size_hint: None, None
                size: dp(40), dp(40)
                pos_hint: {"center_y": 0.5}
                background_color: 0, 0, 0, 0
                on_press: print("WhatsApp")

                Image:
                    source: "image/whatsapp-24.png"
                    size: dp(32), dp(32)
                    size_hint: None, None
                    center: self.parent.center

            Button:
                size_hint: None, None
                size: dp(40), dp(40)
                pos_hint: {"center_y": 0.5}
                background_color: 0, 0, 0, 0
                on_press: print("Appeler")

                Image:
                    source: "image/appel-24.png"
                    size: dp(32), dp(32)
                    size_hint: None, None
                    center: self.parent.center