#:import MapView kivy_garden.mapview.MapView
#:import MapMarkerPopup kivy_garden.mapview.MapMarkerPopup

<Mymap>:
    FloatLayout:
        MapView:
            size_hint : 1, 1
            pos_hint:{"x" :0,"y":0}
            lat: 36
            lon: -115
            zoom: 13

            MapMarkerPopup:
                lat: 36
                lon: -115

                Label:
                    text: "Mon marqueur"
                    size_hint: None, None
                    size: 100, 40
                
 