<Mymap>:
    # Liaison des propriétés
    mapview: mapview_widget
    bar_recherche: bar_recherche_widget
    
    FloatLayout:
        MapView:
            id: mapview_widget  # ← ID important !
            lat: -18.8792
            lon: 47.5079
            zoom: 10
        
        Bar_de_recherche:
            id: bar_recherche_widget  # ← ID important !
            mapview: mapview_widget  # ← LIAISON CRUCIALE !
            pos_hint: {"center_x": 0.5, "top": 0.98}
            size_hint: 0.9, None
            height: "50dp"