#:import PageAcc pageAcc
#:import Mymap map2
#:import NavigationScreenManager Navigation_screen_Manager
#:import ProgressBarWidget Progress_bar
#:import navigation_bar Navigation_bar
#:import Bar_de_recherche Bar_de_recherche
#:import DetailTaximoto DetailTaximoto
#import BarreRetour barreRetour
#:import PageNotification Page_Notification


<MyScreenManager>:
    Screen:
        name: "PageAccuil"
        BoxLayout:
            Button:
                id: btn_container   
                disabled: True
                opacity:0
                pos_hint:{ "right": .5 }
                size_hint: None, None
                #size: "100dp", "60dp"
                width: "100dp"
                height:"60dp"
                text:">"
                on_press: app.manager.push("Mymap")
        PageAcc:
            #Eto zany dia mandeha ao @ le fonction push ilay Button d pusheny ao anaty tableau ilay izy

    DetailTaximoto:
        name: "detailMoto" 

        BarreRetour:
            size_hint:1, None

        FloatLayout:
            NavigationBar:                         
                size_hint_y: None
                height: dp(70)
                pos_hint: {"x": 0, "y": .02}   

    Screen :
        name: "notif"
        PageNotification:
        
    Screen :
        name:"Mymap"
        #NavigationBar:
        #title:"mymap"
        Mymap:
            NavigationBar
            #Bar_de_recherche
    Screen:
        name:"MotoWidget"
        MotoWidget:

    PostScreen:
        name: "postscreen"
    ListScreen:
        name: "list"
        
    DemandePublication:
        name: "Demande"

    MainWidget:
        name:"liste_moto"
        BarreRetour:
            size_hint:1, None
             

        FloatLayout:
            NavigationBar:                         
                size_hint_y: None
                height: dp(70)
                pos_hint: {"x": 0, "y": .02}    

    Screen:
        name: "detailMoto"
        DetailTaximoto:
        FloatLayout:
            NavigationBar:                         
                size_hint_y: None
                height: dp(70)
                pos_hint: {"x": 0, "y": .02}     

    Screen:
        name: "Screen2"
        Button:
            text:"Button2"
            on_press: app.manager.pop()

    
    
    