#:import PageAcc pageAcc
#:import Mymap map2
#:import NavigationScreenManager Navigation_screen_Manager
#:import ProgressBarWidget Progress_bar
#:import navigation_bar Navigation_bar

#ProgressBarWidget:
#Mymap:
#PageAcc:

<MyScreenManager>:
    Screen:
        name: "PageAccuil"
        PageAcc:
            #Eto zany dia mandeha ao @ le fonction push ilay Button d pusheny ao anaty tableau ilay izy

    Screen :
        name:"Mymap"
        NavigationBar:
            #title:"mymap"
            Mymap:

    Screen:
        name: "Screen2"
        Button:
            text:"Button2"
            on_press: app.manager.pop()
    
    