#: set sx dp(500) #declaration d' une variable dans un fichir kv
#: set sy dp(62)
#:import Mymap map2
<NavigationBar>:
    BoxLayout:
        size_hint: .95, None
        height: "50dp"
        width : "330dp"
        pos_hint: {"center_x": .5, "y": .03}
        canvas.before:
            Color:
                rgba: 12/255, 24/255, 75/255, 1  # bleu foncé
            RoundedRectangle:
                pos: self.pos
                size: self.size
                radius: [25]

        Button: 
            background_color: 0, 0, 0, 0
            color: 1, 1, 1, 
            height: "50dp"
            width : "330dp"
            icon: "home"
            on_press: app.manager.pop()
            Image:
                source:"image/icons8-accueil-128.png"
                size:"24dp","24dp"
                center:self.parent.center

        Button:
            #text: "post"
            background_color: 0, 0, 0, 0
            height: "50dp"
            width : "330dp"
            on_press: app.naviguer_demande() 
            Image: 
                source: "image/icons8-ajouter-96.png"
                size:"24dp","24dp"
                center:self.parent.center

        Button:
            #text: "notif"
            background_color: 0, 0, 0, 0
            height: "50dp"
            width : "330dp"
            on_press: app.manager.push("notif")
            Image: 
                source: "image/icons8-rappels-de-rendez-vous-100.png"
                size:"24dp","24dp"
                center:self.parent.center
        Button:
            background_color: 0, 0, 0, 0
            height: "50dp"
            width : "330dp"
            on_press:app.manager.push("liste_moto") 
            Image: 
                source: "image/icons8-liste-100.png"
                size:"24dp","24dp"
                center:self.parent.center

