<PageNotification>:
    orientation: "vertical"
    

    MDTopAppBar:
        title: "Notification"
        md_bg_color: 0.05, 0.1, 0.3, 1
        specific_text_color: 1, 1, 1, 1
        left_action_items: [["arrow-left", lambda x : app.go_main()]]
        ###right_action_items: [["format-list-bulleted", lambda x: app.go_list()]]

    MDLabel:
        text: "Contenu Vide"
        halign: "center"