<PageAcc>:
    cols:1
    MDBoxLayout:
        orientation: "vertical"
        
        MDBoxLayout:
            orientation: "vertical"
            spacing: "10dp"
            padding: "20dp"
            
            Widget:
            
            Image:
                source: "image/image_logo.jpeg"
                size_hint: None, None
                size: "200dp", "200dp"
                pos_hint: {"center_x": 0.5}
            
            Label:
                text: "Taxi moto"
                font_size: '20dp'
                bold: True
                color: 0, 0, 0, 1
                size_hint_y: None
                height: "30dp"
                halign: "center"
            

            BoxLayout:
                size_hint_y: None
                height: "20dp"
                

                Widget:
                
                ProgressBar:
                    id: my_progressbar 
                    max: 100
                    value: 0
                    size_hint_x: 0.6
                

                Widget:

            Widget:
