#:import ProgressBarWidget Progress_bar

<PageAcc>:
    cols:1
    MDBoxLayout:
        orientation: "vertical"
        
        MDBoxLayout:
            orientation: "vertical"
            spacing: "10dp"
            padding: "20dp"
            
            Widget:
            
            Image:
                source: "image/L.png"
                size_hint: None, None
                size: "140dp", "129dp"
                pos_hint: {"center_x": 0.5}
            
            Label:
                text: "Taxi moto"
                font_size: '20dp'
                bold: True
                color: 0, 0, 0, 1
                size_hint_y: None
                height: "30dp"
                halign: "center"

            Widget:
            BoxLayout:

                size_hint_y: None
                height: "20dp"
                ProgressBarWidget:
            Widget:
