#:import ProgressBarWidget Progress_bar

<PageAcc>:
    cols:1
    MDBoxLayout:
        orientation: "vertical"
        
        MDBoxLayout:
            orientation: "vertical"
            spacing: "10dp"
            padding: "20dp"
            
            Widget:
            
            Image:
                source: "image/L.png"
                size_hint: None, None
                size: "140dp", "129dp"
                pos_hint: {"center_x": 0.5}
            
            Label:
                text: "Taxi moto"
                font_size: '20dp'
                bold: True
                color: 0, 0, 0, 1
                size_hint_y: None
                height: "30dp"
                halign: "center"
            Widget:
            Button:
                text: "Passer"
                color: 1, 1, 1, 1
                background_color: 0, 0, 0, 0  # transparent pour cacher le fond par défaut
                size_hint: 1, None
                height: "50dp"
                width : "330dp"
                pos_hint: {"center_x": .5}
                on_press: app.manager.push("Mymap")
                canvas.before:
                    Color:
                        rgba: 12/255, 24/255, 75/255, 1
                    RoundedRectangle:
                        pos: self.pos
                        size: self.size
                        radius: [25]
        